services:
  database:
    image: postgres:17
    container_name:
      br_e_commerce_dwh
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: br_e_commerce_dwh
    ports:
      - "5433:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
volumes:
  pg_volume: